mysite/carrinho/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:brand_id>/', views.detail_brand , name= 'detail_brand')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('carrinho/', include('carrinho.urls')),
]

mysite/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/carrinho/models.py
from django.db import models

class Brand(models.Model):
    brand_name = models.CharField('Nome da marca', max_length=200)
    foundation_Date  = models.DateTimeField('Data de Fundação')

    def __str__(self):
        return self.brand_name

    def was_published_recently(self):
        return self.foundation_Date >= timezone.now() - datetime.timedelta(days=1)


class Car(models.Model):
    brand = models.ForeignKey( Brand, on_delete=models.CASCADE)
    car_name = models.CharField('Nome do carro', max_length=200)
    value_car = models.IntegerField('Valor do carro', default=0)

    def __str__(self):
        return self.car_name

mysite/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField( max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/carrinho/views.py
from django.shortcuts import render
from .models import Brand
from django.http import HttpResponse


def index(request):
    brand_list = Brand.objects.order_by('-foundation_Date')[:5]
    context = {'brand_list': brand_list}
    return render(request, 'index.html', context)

def detail_brand(request, brand_id):
    brand = Brand.objects.get(id = brand_id)
    return render(request, 'detail.html', {'brand': brand})

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question
from django.template import loader
from django.http import HttpResponse, Http404

# Create your views here.

def index(request):
    #Modo ruim de renderizar
    """latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = '<br> <br>'.join([q.question_text for q in latest_question_list])
    return HttpResponse(output)"""

    #Modo completo
    """latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))"""

    #Modo reduzido
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    #Modo completo
    """try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist :´)")
    return render(request, 'polls/detail.html', {'question': question})"""

    #Modo reduzido
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

mysite/carrinho/templates/detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{{ brand.brand_name}}</title>
</head>
<body>
    <h1> {{ brand.brand_name}} </h1>
    <ul>
        {% for car in brand.car_set.all%}
            <li>
                <span>{{ car.car_name}}</span>
                <span> R$ {{ car.value_car }} </span>
            </li>
        
        {% endfor%}
    </ul>
</body>
</html>

mysite/carrinho/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Loja de carros</title>
</head>
<body>
    {% if brand_list %}
        <h1>Bem vindo a Loja de carros de Rafael :) </h1>
        <br><br>
        <h2>Essas são as marcas disponiveis</h2>
        <ol>
            {% for brand in brand_list %}
                <li><a href="/carrinho/{{ brand.id }}/">{{ brand.brand_name }}</a></li>
            {% endfor %}
        </ol>
        {% else %}
            <p>No polls are available.</p>
    {% endif %}

</body>
</html>

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>
                <span>{{ choice.choice_text }}</span>
                <span> {{ choice.votes }}</span>
            </li>
        {% endfor %}
    </ul>

</body>
</html>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <h1>Bem vindo a votação de Rafael :) </h1>
    <br>
    <br>
    <h2>Essas são as enquetes disponiveis</h2>
    <ol>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No polls are available.</p>
{% endif %}